-- 코드를 입력하세요
# 2021년 가입한 유저 출력하기
# SELECT USER_ID
# FROM USER_INFO
# # WHERE DATE_FORMAT(JOINED, '%Y') = '2021';
# WHERE YEAR(JOINED) = 2021;

# 2021년 가입한 유저들의 ONLINE_SALE 테이블 출력하기
# SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE USER_ID IN (SELECT USER_ID
#                  FROM USER_INFO
#                  WHERE DATE_FORMAT(JOINED, '%Y') = '2021');
                 
# 1단계 세팅
# SELECT 
# FROM USER_INFO U
# JOIN ONLINE_SALE O
# ON USER U.USER_ID = O.USER_ID
# WHERE YEAR(U.JOINED) = 2021
# GROUP BY YEAR(0.SALES_DATE), MONTH(O.SALES_DATE)
# ORDER_BY YEAR(0.SALES_DATE), MONTH(O.SALES_DATE);


# 2단계 세팅
SELECT DATE_FORMAT(O.SALES_DATE, '%Y') AS YEAR, # 년, 월을 출력하는 2가지 방식
       MONTH(O.SALES_DATE) AS MONTH,
       COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS, # 이미 2021 JOIN한 사람으로 묶어두었으니 DISTINCT로 중복 제거
       ROUND(
            (COUNT(DISTINCT U.USER_ID)) / 
            (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)=2021) #()를 해줘야 함
            ,1) AS PURCHASED_RATIO # 1은 소수점 1자리까지 표시한다는 뜻
       
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021 # WHERE U.JOINED like "2021%" 도 가능
GROUP BY YEAR, MONTH # SELECT 문에서 YEAR, MONTH를 정의해두었기 때문
ORDER BY YEAR, MONTH;